### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by pmbrug** [jean-knapp/windows-source-modding-tool#52] opened 2021-11-06 17:37 UTC
I get an error saying: "An item with the same key has already been added."
other details: "See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at SourceSDK.Launcher.LoadGames() in D:\Files\Development\CS\windows-source-modding-tool\SourceSDK\Launcher.cs:line 68
   at source_modding_tool.MainForm.updateToolsGames()
   at source_modding_tool.MainForm.Form_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
XBLAH's Modding Tool
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/mpbru/Desktop/XBLAH%20Modding%20Creator/XBLAH's%20Modding%20Tool.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevExpress.Utils.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///C:/Users/mpbru/Desktop/XBLAH%20Modding%20Creator/Libs/DevExpress.Utils.v20.2.DLL
----------------------------------------
DevExpress.Data.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///C:/Users/mpbru/Desktop/XBLAH%20Modding%20Creator/Libs/DevExpress.Data.v20.2.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
DevExpress.Data.Desktop.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///C:/Users/mpbru/Desktop/XBLAH%20Modding%20Creator/Libs/DevExpress.Data.Desktop.v20.2.DLL
----------------------------------------
DevExpress.XtraBars.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///C:/Users/mpbru/Desktop/XBLAH%20Modding%20Creator/Libs/DevExpress.XtraBars.v20.2.DLL
----------------------------------------
DevExpress.XtraEditors.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///C:/Users/mpbru/Desktop/XBLAH%20Modding%20Creator/Libs/DevExpress.XtraEditors.v20.2.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
SourceSDK
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Users/mpbru/Desktop/XBLAH%20Modding%20Creator/Libs/SourceSDK.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box."
I do not know what to do and
maybe I may not be able to use it.
Can you HELP!
Also chack out the same issue: https://github.com/jean-knapp/windows-source-modding-tool/issues/51

**Comment by pmbrug** [comment] 2021-11-06 17:39
I do not know what this dumb robot code is.
But it might be helpful if 
I learn it.

**Comment by Fennecai** [comment] 2021-11-06 20:47
> I do not know what this dumb robot code is. But it might be helpful if I learn it.

please stop replying with useless crap to this issue. you don't know what your talking about and you did the same thing on my original issue which was the same problem.

this is a duplicate of #51

**Comment by Fennecai** [comment] 2021-11-06 20:52
same issue as what I posted.

**Comment by jean-knapp** [comment] 2021-11-22 01:29
By any chance do you have two Half-Life 2 folders in your Steam libraries? Because this error is associated with this:

![image](https://user-images.githubusercontent.com/81480122/142788063-8cdb6eb3-90cd-4430-9393-a473f96e6c42.png)

When it reads a folder called half-life 2, it adds a game called Half-Life 2. That error is happening because apparently you also have a game folder caled Half-Life 2.

I'll add a helper message for this in the next version, so it may help you troubleshoot it.

**Closed** 2021-11-22 01:32 UTC
