### ISSUE TITLE
Unhandled exception: An item with the same key has already been added (and nothing works at all afterwards)

### ISSUE THREAD

**Issue by Fennecai** [jean-knapp/windows-source-modding-tool#51] opened 2021-10-30 18:08 UTC
happens as soon as i start the program up.

![image](https://user-images.githubusercontent.com/10889213/139550931-1341c6c1-4461-48aa-a2a3-02d4e656737f.png)

Details:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at SourceSDK.Launcher.LoadGames() in D:\Files\Development\CS\windows-source-modding-tool\SourceSDK\Launcher.cs:line 38
   at source_modding_tool.MainForm.updateToolsGames()
   at source_modding_tool.MainForm.Form_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
XBLAH's Modding Tool
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///G:/Tools/modification/Source%20engine/mod%20tools/XBLAH's%20Modding%20Tool.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevExpress.Utils.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///G:/Tools/modification/Source%20engine/mod%20tools/Libs/DevExpress.Utils.v20.2.DLL
----------------------------------------
DevExpress.Data.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///G:/Tools/modification/Source%20engine/mod%20tools/Libs/DevExpress.Data.v20.2.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
DevExpress.Data.Desktop.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///G:/Tools/modification/Source%20engine/mod%20tools/Libs/DevExpress.Data.Desktop.v20.2.DLL
----------------------------------------
DevExpress.XtraBars.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///G:/Tools/modification/Source%20engine/mod%20tools/Libs/DevExpress.XtraBars.v20.2.DLL
----------------------------------------
DevExpress.XtraEditors.v20.2
    Assembly Version: 20.2.6.0
    Win32 Version: 20.2.6.0
    CodeBase: file:///G:/Tools/modification/Source%20engine/mod%20tools/Libs/DevExpress.XtraEditors.v20.2.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
SourceSDK
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///G:/Tools/modification/Source%20engine/mod%20tools/Libs/SourceSDK.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

in addition, if I continue instead of quitting, nothing works at all, constantly throwing similar exceptions:
![image](https://user-images.githubusercontent.com/10889213/139552476-2b0be850-5cce-430d-9e1f-2ae766c3a429.png)

I suspect it has something to maybe do with the duplicate library entry, causing mods to not be found and such, but I cant remove the duplicate because the X is greyed out: 
![image](https://user-images.githubusercontent.com/10889213/139553670-804232a3-bfeb-47f2-9086-b1b2da9a33f2.png)

**Comment by ZeqMacaw** [comment] 2021-11-02 13:07
Looking quickly through the source code, I would guess that in the folder where the tool's EXE is, there is a "libraryfolders.vdf" file that contains the text "E:\Antonios stuff\program files\Steam". This is likely a duplicate of what your Steam already has and why that path is listed twice in the Libraries window as shown in one of the posted images. Thus, to get around the error, delete the "libraryfolders.vdf" file. 

However, the error might show up again because the tool might have another bug where it incorrectly creates that file. Or, maybe that file was created from a previous version.

**Comment by Fennecai** [comment] 2021-11-02 13:45
> However, the error might show up again because the tool might have another bug where it incorrectly creates that file.

I think it's something like this but not exactly. I have no file like that in the exe's folder, and no new one is ever created automatically...except for some reason I do remember it being there one time.

it's worth noting that I have completely deleted the contents of the folder and re-downloaded everything multiple times trying to make it work. 

so that file doesn't exist in the exe folder, and it doesn't usually get re-made either, so...

**Comment by pmbrug** [comment] 2021-11-06 14:19
Maybe you need Microsoft .NET

**Comment by pmbrug** [comment] 2021-11-06 17:23
Or you can go into \tools\"whatever tool you are looking for"\"tool".exe or "tool".jar

**Comment by Fennecai** [comment] 2021-11-06 20:46
i already have the .net framework. that suggestion has nothing to even remotely do with the problem, either.

**Comment by Fennecai** [comment] 2021-11-06 20:50
#51 is the same problem

**Comment by jean-knapp** [comment] 2021-11-22 01:35
There will be a Message Box stating why this is happening and what you should do to fix this in the next update. Reopen the issue if it's not solved.

**Closed by jean-knapp** 2021-11-22 01:35 UTC

**Comment by Fennecai** [comment] 2021-11-22 15:15
not resolved sadly... 
![image](https://user-images.githubusercontent.com/10889213/142886347-d1949690-67d1-4982-acfd-08cdef3cfcb5.png)
i dont know what it actually means by hl2 being loaded in "Sourcesdk.game"...

i tried deleting the entire contents of my source SDK folder in steamapps/common but that didn't work and it kept throwing this message every time I did anything in the app, until I tried editing a soundscape and got the old "null reference" exception
